# Generated by Django 2.2.3 on 2019-07-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
